### ISSUE TITLE
zotra-cli fails to add some URLs

### ISSUE THREAD

**Issue by benthamite** [mpedramfar/zotra-cli#2]
It appears that zotra-cli is unable to add certain URLs which load fine when `zotra-backend` is set to `translation-server`. [Here is an example](https://www.philosophyetc.net/2021/01/theres-no-such-thing-as-following.html). Most other URLs are added without a problem.

Can you check if this is also an issue on your end? If not, I'm happy to provide further details about my zotra/zotra-cli config.

**Comment by mpedramfar** [comment]
Closing since this seems to be the same issue as [zotra#9](https://github.com/mpedramfar/zotra/issues/9).
