### ISSUE TITLE
Cannot find module "config" upon install

### ISSUE THREAD

**Issue by yaqubroli** [mpedramfar/zotra-cli#3]
When I try and install `zotra-cli` with `npm install -g .` in the cloned directory, it initially gave this error:

```
% zotra
node:internal/modules/cjs/loader:1051
  throw err;
  ^

Error: Cannot find module 'config'
Require stack:
- /Users/yaqub/Library/Mobile Documents/com~apple~CloudDocs/Development/zotra-cli/bin/index.js
- ...
```

Note that the require stack contained *my personal development directory* that I cloned this repo to, not where my node modules are actually stored systemwide (`/opt/homebrew/lib/node_modules`.) In fact, if I go there, I do see a `zotra` directory, but it only contains the `src` folder, and thus only `attachments.js`. I am assuming this is not intended behaviour, so I added the following to package.json:

```
  "files": [
    "bin",
    "config",
    "module",
    "src"
  ],
```

After that, all of the folders were safely in the `zotra/` directory in node-modules, but when I ran `zotra` from the command line, it still got the above error (complete with a stack trace *still* referencing my development folder). Despite this, the actual `zotra` command itself seems to be referring now to the `bin/index.js` in my systemwide `node_modules`.

```
% which zotra
/opt/homebrew/bin/zotra
% ls -l /opt/homebrew/bin/zotra
lrwxr-xr-x  1 yaqub  admin  38 22 Aug 14:38 /opt/homebrew/bin/zotra -> ../lib/node_modules/zotra/bin/index.js
```

I am not sure what's going on here; either this is me screwing up (quite likely) or there is code in index.js that uses some kind of environment variable that isn't activated when npm is installed through homebrew, maybe?

**Comment by yaqubroli** [comment]
It appears that it works fine when installed locally and not in system-wide node_modules, so I'm employing that as a temporary solution for now. While I think the `config` error might be a red herring (I'm assuming it's referring to the `config` in the repo and not the npm package of the same name,) something about global installation is not resolving on my system.

Notably, I tried with `nvm` instead of node installed through Homebrew, and it still gave me this error. I'm on macOS Ventura 14.3.1.

This is the message I see (after the some deprecated warnings and stuff) when I install locally: `added 387 packages, and audited 389 packages in 11s`.

Whereas globally it seems to not even get that there's dependencies and just say `added 1 package in 88ms`.

**Comment by gwbrck** [comment]
For me, the global installation also only worked if I installed local first.

**Comment by mpedramfar** [comment]
A similar issue seems to happen in [Windows](https://github.com/mpedramfar/zotra/issues/11#issuecomment-1684924323) as well. My guess is that it's about some environment variable.

Seems like global installation of nodejs packages is a mess. On both macOS and Windows, it's tricky and on Linux by default it would need root access. I'll change the README to say local install is the recommended method.

**Comment by cashpw** [comment]
I'm getting this error as well on a fresh install:

```shell
npm start

> zotra@1.0.0 start
> node bin/index.js server

node:internal/modules/cjs/loader:1404
  throw err;
  ^

Error: Cannot find module 'config'
Require stack:
- /home/cashweaver/proj/dotfiles/local/share/zotra-server/bin/index.js
    at Function._resolveFilename (node:internal/modules/cjs/loader:1401:15)
    at defaultResolveImpl (node:internal/modules/cjs/loader:1057:19)
    at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1062:22)
    at Function._load (node:internal/modules/cjs/loader:1211:37)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:235:24)
    at Module.require (node:internal/modules/cjs/loader:1487:12)
    at require (node:internal/modules/helpers:135:16)
    at Object.<anonymous> (/home/cashweaver/proj/dotfiles/local/share/zotra-server/bin/index.js:7:16)
    at Module._compile (node:internal/modules/cjs/loader:1730:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/cashweaver/proj/dotfiles/local/share/zotra-server/bin/index.js'
  ]
}

Node.js v22.15.0
```

**Comment by cashpw** [comment]
Fixed with `npm install --save config`.
